# Generated by Django 4.1.2 on 2022-12-01 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Journal_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'journal_entry',
            },
        ),
        migrations.CreateModel(
            name='Journal_Entry_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'journal_entry_type',
            },
        ),
        migrations.CreateModel(
            name='Measurement_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'measurement_type',
            },
        ),
        migrations.CreateModel(
            name='Modify_Info_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'modify_info_entry',
            },
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbidity_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'morbidity',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.CharField(blank=True, max_length=13)),
                ('user_gender', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Accountability_Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutritiontracker.user')),
                ('relationship', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'accountability_partner',
            },
            bases=('nutritiontracker.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutritiontracker.user')),
                ('doctor_specialization', models.CharField(blank=True, max_length=20)),
                ('doctor_license', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'doctor',
            },
            bases=('nutritiontracker.user',),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('modify_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.modify_info_entry')),
            ],
            options={
                'db_table': 'weight',
            },
        ),
        migrations.CreateModel(
            name='Morbidity_Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbidity_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.morbidity')),
                ('stage_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.stage')),
            ],
            options={
                'db_table': 'morbidity_stage',
            },
        ),
        migrations.CreateModel(
            name='Journal_Line_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.journal_entry')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.item')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.journal_entry_type')),
            ],
            options={
                'db_table': 'journal_line_item',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='measurement_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.measurement_type'),
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feet', models.IntegerField()),
                ('inches', models.IntegerField()),
                ('modify_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.modify_info_entry')),
            ],
            options={
                'db_table': 'height',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutritiontracker.user')),
                ('patient_DOB', models.DateField(help_text='Date of birthday')),
                ('patient_race', models.CharField(max_length=20)),
                ('doctor_id', models.ManyToManyField(blank=True, to='nutritiontracker.doctor')),
                ('partner_id', models.ManyToManyField(blank=True, to='nutritiontracker.accountability_partner')),
            ],
            options={
                'db_table': 'patient',
            },
            bases=('nutritiontracker.user',),
        ),
        migrations.AddField(
            model_name='modify_info_entry',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.patient'),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.patient'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('modify_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nutritiontracker.modify_info_entry')),
                ('morbidity_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nutritiontracker.morbidity_stage')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
    ]
