# Generated by Django 4.1.2 on 2022-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritiontracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_line_item',
            name='phosophorus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_line_item',
            name='potassium',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_line_item',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_line_item',
            name='sodium',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_line_item',
            name='water',
            field=models.FloatField(null=True),
        ),
    ]
